### ISSUE TITLE
Don't put SSL certs in the data dir

### ISSUE THREAD

**Issue by krallin** [aptible/docker-mysql#16]
Currently, we auto-generate SSL certs at startup and drop them in the data directory. As of MySQL 5.7, this doesn't fly, with MySQL (understandably) complaining about extra files in its data dir.

Any objections to just moving them out and auto-generating them at startup instead of keeping them around in the data dir?

cc @fancyremarker @aaw 

For some context, this was added in: 7d3c94a6d64e5641b57f3e037091989dd56fba49

Cheers,

**Comment by fancyremarker** [comment]
@krallin: As discussed, I have no objections to this, and agree it is the correct approach.
